name: CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Jest tests
      run: yarn test
    - name: Run Jest test coverage
      run: yarn test --coverage
